set allow-duplicate-recipes := true
set ignore-comments := true

product_name := `cat /sys/devices/virtual/dmi/id/product_name`
sys_vendor := `cat /sys/devices/virtual/dmi/id/sys_vendor`

_default:
    @just --list --list-heading $'Available commands:\n' --list-prefix $' - '

# Imports

import "/usr/share/sk-chos/just/00-default.just"
import "/usr/share/sk-chos/just/20-clean.just"
import "/usr/share/sk-chos/just/40-nix.just"

import "/usr/share/sk-chos/just/80-chos.just"
import "/usr/share/sk-chos/just/81-chos-apps.just"
import "/usr/share/sk-chos/just/81-chos-asus.just"
import "/usr/share/sk-chos/just/81-chos-decky.just"
import "/usr/share/sk-chos/just/81-chos-fixes.just"

# vim: set ft=make :