#!/bin/bash

set -e

if [ "$EUID" -ne 0 ]; then
    echo "This script must be run as root or with sudo."
    exit 1
fi

PRODUCT=$(cat "/sys/class/dmi/id/product_name")

AIR_1S_LIST="AIR 1S:AIR 1S Limited"
AIR_PLUS_LIST="AIR Plus"

AW87559_LIST="$AIR_1S_LIST:$AIR_PLUS_LIST"

sys_symbolic="/usr/lib/firmware/aw87xxx_acf.bin"
user_symbolic="/etc/device-quirks/firmware/aw87xxx_acf.bin"

if [ ! -d "/etc/device-quirks/firmware/" ]; then
    mkdir -p "/etc/device-quirks/firmware/"
fi

aw87559_firmware="/usr/lib/firmware/aw87xxx/aw87559/awinic_smartk_acf.bin"
if [[ ":$AW87559_LIST:" =~ ":$PRODUCT:" && -e "$aw87559_firmware" ]]; then
    real_path="$aw87559_firmware"
fi

if [ -z "$real_path" ]; then
    echo "Not need to create link"
    exit 0
fi

if [[ -L "$user_symbolic" ]]; then
    current_real_path=$(readlink -f "$user_symbolic")
    if [[ "$current_real_path" != "$real_path" ]]; then
        echo "Remove old link $user_symbolic, and create new link to $real_path"
        rm -f "$user_symbolic"
        ln -sf "$real_path" "$user_symbolic"
    fi
else
    echo "Create link $user_symbolic to $real_path"
    ln -sf "$real_path" "$user_symbolic"
fi

if [ ! -e "$sys_symbolic" ]; then
    echo "Create link $sys_symbolic to $user_symbolic"
    ln -sf "$user_symbolic" "$sys_symbolic"
elif [ -L "$sys_symbolic" ]; then
    dest_path=$(readlink "$sys_symbolic")
    if [ "$dest_path" != "$user_symbolic" ]; then
        echo "Remove old link $sys_symbolic, and create new link to $user_symbolic"
        rm -f "$sys_symbolic"
        ln -sf "$user_symbolic" "$sys_symbolic"
    fi
else
    echo "Remove old file $sys_symbolic, and create new link to $user_symbolic"
    rm -f "$sys_symbolic"
    ln -sf "$user_symbolic" "$sys_symbolic"
fi
