#!/bin/bash

set -e

umaf_boot=$(efibootmgr | grep "UMAF" | grep "umaf.efi" | awk '{print $1}'| sed 's/Boot//' | sed 's/\*//')
if [ -z "$umaf_boot" ]; then
    echo "UMAF boot entry not found, creating one..."
    /usr/libexec/setup-umaf
else
    echo "UMAF boot entry $umaf_boot found, set to next boot..."
    efibootmgr -n $umaf_boot
    sleep 1
    reboot
fi