#!/usr/bin/bash

# from https://github.com/ublue-os/bazzite/blob/main/system_files/desktop/shared/usr/libexec/waydroid-fix-controllers

echo "add" | sudo tee /sys/devices/virtual/input/input*/event*/uevent