

post_install() {
    echo "Penable sk-auto-swap.service and sk-efi-mount.service"
    sudo systemctl enable sk-auto-swap.service
    sudo systemctl enable sk-efi-mount.service

    # swap partuuid
    echo "set swap PARTUUID in /etc/default/auto_swap"
    SWAP_PARTITION=$(lsblk -rno NAME,PARTUUID,PARTTYPE | awk '$3=="0657fd6d-a4ab-43c4-84e5-0933c84b4f4f" {print $1}')
    echo "$SWAP_PARTITION" | sudo tee /etc/default/auto_swap
}