#!/bin/bash

# Device specific configs
DEVICENAME=$(cat /sys/devices/virtual/dmi/id/product_name)
VENDOR=$(cat /sys/devices/virtual/dmi/id/sys_vendor)
SCREEN_MODEL_NAME=$(cat /sys/class/drm/card*-eDP-1/edid | parse-edid 2>/dev/null | grep "ModelName" | cut -d \" -f 2 | sed 's/[^a-zA-Z0-9_-]//g')

X11_ROTATION="normal"
video=""

AYA_RIGHT_LIST=(
    "AYA NEO FOUNDER"
    "AYA NEO 2021"
    "AYANEO 2021"
    "NEXT"
    "AYANEO 2"
    "GEEK"
)

AYA_LEFT_LIST=(
    "AIR"
    "SLIDE"
    "FLIP"
)

LGO_LEFT_LIST=(
    "83E1"
)

GPD_RIGHT_LIST=(
    "G1617-01"
    "G1621-02"
    "G1619-01"
    "MicroPC"
)

AOKZOE_LEFT_LIST=(
    "AOKZOE A1"
    "AOKZOE A2"
)

ONEXPLAYER_LEFT_LIST=(
    "ONE XPLAYER"
    "ONEXPLAYER 1"
    "ONEXPLAYER GUNDAM"
    "ONEXPLAYER Mini"
    "ONEXPLAYER mini"
    "ONEXPLAYER F1"
    "ONEXPLAYER 2"
)

AYN_LEFT_LIST=(
    "Loki Max"
    "Loki MiniPro"
    "Loki Zero"
)

# LEFT_LIST="${OXP_LIST}:${AIR_LIST}:${AOK_LIST}:${AYN_LIST}:${LENOVO_LIST}"
# RIGHT_LIST="${AYA_LIST}:${GPD_LIST}"

LEFT_LIST=(
    "${AYA_LEFT_LIST[@]}"
    "${LGO_LEFT_LIST[@]}"
    "${AOKZOE_LEFT_LIST[@]}"
    "${ONEXPLAYER_LEFT_LIST[@]}"
    "${AYN_LEFT_LIST[@]}"
)

RIGHT_LIST=(
    "${AYA_RIGHT_LIST[@]}"
    "${GPD_RIGHT_LIST[@]}"
)

NORMAL_MODEL_LIST=(
    "TL070FVXS01"
    "TL070FVXS02"
    "TL070FDXS01"
    "PN8007QB1"
    "NS080WUM"
)

ROTATE_OFFSET="0"

for product in "${LEFT_LIST[@]}"; do
    if [[ "$DEVICENAME" =~ "$product" ]]; then
        ROTATE_OFFSET="3"
        X11_ROTATION="left"
        video="eDP-1:panel_orientation=left_side_up"
        break
    fi
done

for product in "${RIGHT_LIST[@]}"; do
    if [[ "$DEVICENAME" =~ "$product" ]]; then
        ROTATE_OFFSET="1"
        X11_ROTATION="right"
        video="eDP-1:panel_orientation=right_side_up"
        break
    fi
done

# 不进行旋转的屏幕
for model in "${NORMAL_MODEL_LIST[@]}"; do
    if [[ "$SCREEN_MODEL_NAME" =~ "$model" ]]; then
        ROTATE_OFFSET="0"
        X11_ROTATION="normal"
        unset video
        break
    fi
done

export FBCON_PARA="rotate:$ROTATE_OFFSET"
export VIDEO_PARA="$video"
export ROTATE_OFFSET=$ROTATE_OFFSET
export X11_ROTATION=$X11_ROTATION
