#!/bin/bash

# Device specific configs
DEVICENAME=$(cat /sys/devices/virtual/dmi/id/product_name)
VENDOR=$(cat /sys/devices/virtual/dmi/id/sys_vendor)
SCREEN_MODEL_NAME=$(cat /sys/class/drm/card1-eDP-1/edid | parse-edid 2>/dev/null | grep "ModelName" | cut -d \" -f 2 | sed 's/[^a-zA-Z0-9-_]//g')

AYA_RIGHT_LIST=(
    "AYA NEO FOUNDER"
    "AYA NEO 2021"
    "AYANEO 2021"
    "NEXT"
    "AYANEO 2"
    "GEEK"
)

AYA_LEFT_LIST=(
    "AIR"
    "SLIDE"
    "FLIP"
)

LGO_LEFT_LIST=(
    "83E1"
)

GPD_RIGHT_LIST=(
    "G1617-01"
    "G1621-02"
    "G1619-01"
    "MicroPC"
)

AOKZOE_LEFT_LIST=(
    "AOKZOE A1"
    "AOKZOE A2"
)

ONEXPLAYER_LEFT_LIST=(
    "ONE XPLAYER"
    "ONEXPLAYER 1"
    "ONEXPLAYER GUNDAM"
    "ONEXPLAYER Mini"
    "ONEXPLAYER mini"
    "ONEXPLAYER F1"
    "ONEXPLAYER 2"
)

AYN_LEFT_LIST=(
    "Loki Max"
    "Loki MiniPro"
    "Loki Zero"
)

# LEFT_LIST="${OXP_LIST}:${AIR_LIST}:${AOK_LIST}:${AYN_LIST}:${LENOVO_LIST}"
# RIGHT_LIST="${AYA_LIST}:${GPD_LIST}"

LEFT_LIST=(
    "${AYA_LEFT_LIST[@]}"
    "${LGO_LEFT_LIST[@]}"
    "${AOKZOE_LEFT_LIST[@]}"
    "${ONEXPLAYER_LEFT_LIST[@]}"
    "${AYN_LEFT_LIST[@]}"
)

RIGHT_LIST=(
    "${AYA_RIGHT_LIST[@]}"
    "${GPD_RIGHT_LIST[@]}"
)

ROTATE_OFFSET="0"

for vendor in "${LEFT_LIST[@]}"; do
    if [[ "$DEVICENAME" =~ "$vendor" ]]; then
        ROTATE_OFFSET="3"
        break
    fi
done

for vendor in "${RIGHT_LIST[@]}"; do
    if [[ "$DEVICENAME" =~ "$vendor" ]]; then
        ROTATE_OFFSET="1"
        break
    fi
done

# ROG Ally 和 win mini 2024 采用的屏幕
if [[ "$SCREEN_MODEL_NAME" == "TL070FVXS01-0" ]]; then
    ROTATE_OFFSET="0"
fi

if [[ "$ROTATE_OFFSET" != "0" ]]; then
    export FBCON_PARA="rotate:$ROTATE_OFFSET"
fi

video=""

if [[ "$ROTATE_OFFSET" == "1" ]]; then
    video="eDP-1:panel_orientation=right_side_up"
elif [[ "$ROTATE_OFFSET" == "3" ]]; then
    video="eDP-1:panel_orientation=left_side_up"
fi

VIDEO_PARA="$video"

export ROTATE_OFFSET=$ROTATE_OFFSET
